# Generated by Django 4.1.1 on 2022-10-06 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absolwent',
            options={'verbose_name_plural': 'absolwenci'},
        ),
        migrations.AlterModelOptions(
            name='klasa',
            options={'ordering': ['rok_naboru'], 'verbose_name_plural': 'klasy'},
        ),
    ]
