# Generated by Django 4.1.3 on 2022-12-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0002_alter_absolwent_options_alter_klasa_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=255, unique=True)),
                ('plik', models.FileField(upload_to='dokumenty/')),
                ('data_d', models.DateTimeField(auto_now_add=True, verbose_name='dodano')),
            ],
            options={
                'verbose_name_plural': 'dokumenty',
            },
        ),
    ]
