# Generated by Django 4.1.3 on 2022-12-08 08:12

from django.db import migrations, models
import osoby.models


class Migration(migrations.Migration):

    dependencies = [
        ('osoby', '0003_dokument'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokument',
            name='typ',
            field=models.CharField(choices=[('K', 'Lista klas'), ('U', 'Lista uczniów')], default='K', max_length=1),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='plik',
            field=models.FileField(upload_to='dokumenty/', validators=[osoby.models.rozmiar_pliku]),
        ),
    ]
